# Generated by Django 5.2.3 on 2025-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='list_students',
        ),
        migrations.AddField(
            model_name='exam',
            name='list_students',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.profile'),
        ),
    ]
