# Generated by Django 5.2.3 on 2025-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_list_students_exam_list_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
