# Generated by Django 5.2.3 on 2025-08-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0004_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1.0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='exams.exam')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='accounts.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='accounts.profile')),
            ],
        ),
    ]
